# Generated by Django 4.0.6 on 2022-10-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_coachingtime_coachingflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingtime',
            name='groundId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoachingTime', to='api.grounddetails'),
        ),
        migrations.AlterField(
            model_name='grounddetails',
            name='turfId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroundDetails', to='api.turfdetails'),
        ),
        migrations.AlterField(
            model_name='groundimages',
            name='GroundDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroundImages', to='api.grounddetails'),
        ),
        migrations.AlterField(
            model_name='groundpricing',
            name='groundId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroundPricing', to='api.grounddetails'),
        ),
        migrations.AlterField(
            model_name='turfdetails',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turfDetails', to='api.admin'),
        ),
        migrations.AlterField(
            model_name='turfimages',
            name='turfDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfImages', to='api.turfdetails'),
        ),
    ]
