# Generated by Django 4.0.6 on 2022-10-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_coachingtime_groundid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='turfId',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='userId',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='paymentCompletion',
            field=models.CharField(default='after', max_length=225),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='bufferTime',
            field=models.IntegerField(),
        ),
    ]
