# Generated by Django 4.0.6 on 2022-10-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_adminsettings_turfid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='paymentMode',
            field=models.CharField(default='cash', max_length=225),
        ),
    ]
