# Generated by Django 4.0.6 on 2022-10-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_adminsettings_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='paymentCompletion',
            field=models.CharField(default='Before', max_length=225),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='paymentMethod',
            field=models.CharField(default='Advance', max_length=2),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='paymentMode',
            field=models.CharField(default='Online', max_length=225),
        ),
    ]
