# Generated by Django 4.0.6 on 2022-10-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_adminsettings_paymentcompletion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='paymentMethod',
            field=models.CharField(default='Advance', max_length=50),
        ),
    ]
