# Generated by Django 4.0.6 on 2022-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_bookingreport_slotclosingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreport',
            name='paymentMethod',
            field=models.CharField(default='Advance', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentreport',
            name='paymentStatus',
            field=models.CharField(default='Pending', max_length=2),
        ),
    ]
