# Generated by Django 4.0.6 on 2022-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_paymentreport_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreport',
            name='bookingStatus',
            field=models.CharField(default='pending', max_length=125),
        ),
    ]
