# Generated by Django 4.0.6 on 2022-10-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_bookingreport_bookingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreport',
            name='bookedAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
