# Generated by Django 4.0.6 on 2022-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_paymentreport_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreport',
            name='paymentType',
            field=models.CharField(default='online', max_length=125),
        ),
    ]
