# Generated by Django 4.0.6 on 2022-11-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_paymentreport_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreport',
            name='slotPrice',
            field=models.CharField(default=0, max_length=125),
        ),
    ]
