# Generated by Django 4.0.6 on 2022-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_bookingreport_slotprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersaccount',
            name='colorCode',
            field=models.CharField(default='#656BFF', max_length=100),
        ),
    ]
