# Generated by Django 4.0.6 on 2022-11-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_playersaccount_colorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersaccount',
            name='colorCode',
            field=models.CharField(default='#EFF0FF#656BFF', max_length=100),
        ),
    ]
