# Generated by Django 4.0.6 on 2022-11-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_bookingreport_bookedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='grounddetails',
            name='description',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
